# Copyright 2026 Prow Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Initial persister schema: six core tables + indexes.

See docs/design/persister.md (Pass A).
"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy import text

revision: str = "20260513_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))

    op.execute(
        text(
            """
            CREATE TABLE stix_objects (
                row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id text NOT NULL,
                type text NOT NULL,
                spec_version text NOT NULL,
                created timestamptz NOT NULL,
                modified timestamptz NULL,
                created_by_ref text NULL,
                revoked boolean NOT NULL DEFAULT false,
                confidence smallint NULL,
                source_connector_instance_id text NOT NULL,
                ingested_at timestamptz NOT NULL DEFAULT now(),
                raw jsonb NOT NULL,
                search_text tsvector GENERATED ALWAYS AS (
                    to_tsvector(
                        'simple',
                        concat_ws(
                            ' ',
                            coalesce(raw->>'name', ''),
                            coalesce(raw->>'description', '')
                        )
                    )
                ) STORED,
                CONSTRAINT ck_stix_objects_confidence_range CHECK (
                    confidence IS NULL OR (confidence >= 0 AND confidence <= 100)
                )
            )
            """
        )
    )

    op.execute(
        text(
            """
            CREATE UNIQUE INDEX ux_stix_objects_versioned_id_modified
                ON stix_objects (id, modified)
                WHERE modified IS NOT NULL
            """
        )
    )
    op.execute(
        text(
            """
            CREATE UNIQUE INDEX ux_stix_objects_sco_id
                ON stix_objects (id)
                WHERE modified IS NULL
            """
        )
    )

    op.execute(text("CREATE INDEX ix_stix_objects_type ON stix_objects (type)"))
    op.execute(
        text(
            "CREATE INDEX ix_stix_objects_connector ON stix_objects (source_connector_instance_id)"
        )
    )
    op.execute(text("CREATE INDEX ix_stix_objects_ingested_at ON stix_objects (ingested_at)"))
    op.execute(
        text(
            "CREATE INDEX ix_stix_objects_search_text ON stix_objects USING gin (search_text)"
        )
    )
    op.execute(
        text(
            "CREATE INDEX ix_stix_objects_name_trgm ON stix_objects "
            "USING gin (lower(raw->>'name') gin_trgm_ops)"
        )
    )
    op.execute(
        text(
            "CREATE INDEX ix_stix_objects_indicator_pattern ON stix_objects ((raw->>'pattern')) "
            "WHERE type = 'indicator'"
        )
    )
    op.execute(
        text(
            "CREATE INDEX ix_stix_objects_vuln_name_lower ON stix_objects (lower(raw->>'name')) "
            "WHERE type = 'vulnerability'"
        )
    )
    op.execute(
        text(
            "CREATE INDEX ix_stix_objects_malware_name_lower ON stix_objects (lower(raw->>'name')) "
            "WHERE type = 'malware'"
        )
    )

    op.execute(
        text(
            """
            CREATE TABLE stix_relationships (
                id text PRIMARY KEY,
                source_ref text NOT NULL,
                target_ref text NOT NULL,
                relationship_type text NOT NULL,
                created timestamptz NOT NULL,
                modified timestamptz NOT NULL,
                revoked boolean NOT NULL DEFAULT false,
                confidence smallint NULL,
                source_connector_instance_id text NOT NULL,
                ingested_at timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT ck_stix_relationships_confidence_range CHECK (
                    confidence IS NULL OR (confidence >= 0 AND confidence <= 100)
                )
            )
            """
        )
    )
    op.execute(
        text(
            """
            CREATE UNIQUE INDEX ux_stix_relationships_triple
                ON stix_relationships (source_ref, relationship_type, target_ref)
            """
        )
    )
    op.execute(text("CREATE INDEX ix_stix_relationships_source ON stix_relationships (source_ref)"))
    op.execute(text("CREATE INDEX ix_stix_relationships_target ON stix_relationships (target_ref)"))
    op.execute(
        text("CREATE INDEX ix_stix_relationships_type ON stix_relationships (relationship_type)")
    )

    op.execute(
        text(
            """
            CREATE TABLE stix_observables_index (
                value text NOT NULL,
                observable_type text NOT NULL,
                object_id text NOT NULL,
                PRIMARY KEY (value, observable_type, object_id)
            )
            """
        )
    )
    op.execute(text("CREATE INDEX ix_stix_observables_value ON stix_observables_index (value)"))

    op.execute(
        text(
            """
            CREATE TABLE stix_markings (
                object_row_id bigint NOT NULL REFERENCES stix_objects (row_id) ON DELETE CASCADE,
                object_id text NOT NULL,
                marking_id text NOT NULL,
                applied_via text NOT NULL,
                PRIMARY KEY (object_row_id, marking_id, applied_via)
            )
            """
        )
    )
    op.execute(text("CREATE INDEX ix_stix_markings_marking_id ON stix_markings (marking_id)"))
    op.execute(text("CREATE INDEX ix_stix_markings_object_id ON stix_markings (object_id)"))

    op.execute(
        text(
            """
            CREATE TABLE audit_log (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                at timestamptz NOT NULL DEFAULT now(),
                actor_type text NOT NULL,
                actor_id text NULL,
                action text NOT NULL,
                subject_id text NULL,
                details jsonb NULL
            )
            """
        )
    )

    op.execute(
        text(
            """
            CREATE TABLE connector_state (
                connector_instance_id text NOT NULL,
                key text NOT NULL,
                value jsonb NOT NULL,
                updated_at timestamptz NOT NULL,
                PRIMARY KEY (connector_instance_id, key)
            )
            """
        )
    )


def downgrade() -> None:
    op.execute(text("DROP TABLE IF EXISTS stix_markings CASCADE"))
    op.execute(text("DROP TABLE IF EXISTS stix_observables_index CASCADE"))
    op.execute(text("DROP TABLE IF EXISTS stix_relationships CASCADE"))
    op.execute(text("DROP TABLE IF EXISTS stix_objects CASCADE"))
    op.execute(text("DROP TABLE IF EXISTS audit_log CASCADE"))
    op.execute(text("DROP TABLE IF EXISTS connector_state CASCADE"))
    op.execute(text("DROP EXTENSION IF EXISTS pg_trgm CASCADE"))
